### PR TITLE
Make `PersistentSet{T} <: AbstractSet{T}`

### PR DESCRIPTION
**Pull request by georgematheos**

### CODE REVIEW

**Comment by georgematheos** [comment]
@shashi @ararslan are either of you available to review this and hopefully merge into the master branch?  Thanks!

**Review by ararslan — APPROVED** [review]
Thanks for the contribution! These changes look reasonable to me but I haven't touched this package in a long time, so I'd prefer if another set of eyes could take a look as well.

**Comment by georgematheos** [comment]
Any chance this could be merged?  Thanks!

**Comment by georgematheos** [comment]
Thanks!

**Pull request merged**
